<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>npwpFile-label</name>
   <tag></tag>
   <elementGuidId>0cdea5a2-6188-4776-a3d0-56a4e0f24eca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>npwpFile</value>
      <webElementGuid>384aec47-bd71-4f14-8478-8459dad2ae97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datePicker-applyBtn</value>
      <webElementGuid>dc2ee57c-14a3-4587-94af-68df8485c6fc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
