<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//*[@id=&quot;mui-7&quot;]</description>
   <name>chooseBusinessType</name>
   <tag></tag>
   <elementGuidId>72f7742d-83ee-44d5-9b1c-aef14865b2f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;mui-7&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
