<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chooseTaxCity</name>
   <tag></tag>
   <elementGuidId>57fd40f2-1ff0-4a88-ac28-4073bc5ce1d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__next&quot;]/div/div/div/div[2]/div/div/div/div[2]/div/div/div/form/div[1]/div/div[1]/div/div[2]/div/div[5]/div/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
